/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Apresentacao;

/**
 *
 * @author Rever
 */
public class frmPrincipal extends javax.swing.JDialog
{

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuPessoas = new javax.swing.JMenu();
        mniCadastro = new javax.swing.JMenuItem();
        mniPEE = new javax.swing.JMenuItem();
        mnuCarros = new javax.swing.JMenu();
        mniCadastro2 = new javax.swing.JMenuItem();
        mniPEE2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CRUD Pessoas");

        mnuPessoas.setText("Pessoas");

        mniCadastro.setText("Cadastro");
        mniCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadastroActionPerformed(evt);
            }
        });
        mnuPessoas.add(mniCadastro);

        mniPEE.setText("Pesquisa, edição, exclusão");
        mniPEE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPEEActionPerformed(evt);
            }
        });
        mnuPessoas.add(mniPEE);

        jMenuBar1.add(mnuPessoas);

        mnuCarros.setText("Carros");

        mniCadastro2.setText("Cadastro");
        mniCadastro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadastro2ActionPerformed(evt);
            }
        });
        mnuCarros.add(mniCadastro2);

        mniPEE2.setText("Pesquisa, edição, exclusão");
        mniPEE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPEE2ActionPerformed(evt);
            }
        });
        mnuCarros.add(mniPEE2);

        jMenuBar1.add(mnuCarros);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniCadastroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mniCadastroActionPerformed
    {//GEN-HEADEREND:event_mniCadastroActionPerformed
        frmCadastro frmC = new frmCadastro(null, true);
        frmC.setVisible(true);
    }//GEN-LAST:event_mniCadastroActionPerformed

    private void mniPEEActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mniPEEActionPerformed
    {//GEN-HEADEREND:event_mniPEEActionPerformed
        frmPEE frmP = new frmPEE(null, true);
        frmP.setVisible(true);
    }//GEN-LAST:event_mniPEEActionPerformed

    private void mniCadastro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadastro2ActionPerformed
        frmCadastro3 frmC3 = new frmCadastro3(null, true);
        frmC3.setVisible(true);
    }//GEN-LAST:event_mniCadastro2ActionPerformed

    private void mniPEE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPEE2ActionPerformed
        frmPEE2 frmP2 = new frmPEE2(null, true);
        frmP2.setVisible(true);
    }//GEN-LAST:event_mniPEE2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmPrincipal dialog = new frmPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mniCadastro;
    private javax.swing.JMenuItem mniCadastro2;
    private javax.swing.JMenuItem mniPEE;
    private javax.swing.JMenuItem mniPEE2;
    private javax.swing.JMenu mnuCarros;
    private javax.swing.JMenu mnuPessoas;
    // End of variables declaration//GEN-END:variables
}
